name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v1
        with:
          path: bellas-artes-site
      - uses: actions/deploy-pages@v1
